class ErrorCode:
    # Generic
    INVALID_REQUEST = "INVALID_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    # Campaign
    CAMPAIGN_NOT_FOUND = "CAMPAIGN_NOT_FOUND"
    CAMPAIGN_NOT_ACTIVE = "CAMPAIGN_NOT_ACTIVE"
    CAMPAIGN_CLOSED = "CAMPAIGN_CLOSED"
    CAMPAIGN_NOT_OWNER = "CAMPAIGN_NOT_OWNER"
    CAMPAIGN_DEADLINE_PASSED = "CAMPAIGN_DEADLINE_PASSED"
    CAMPAIGN_ALREADY_ACTIVE = "CAMPAIGN_ALREADY_ACTIVE"
    CAMPAIGN_NOT_DRAFT = "CAMPAIGN_NOT_DRAFT"
    CAMPAIGN_DEADLINE_MUST_BE_FUTURE = "CAMPAIGN_DEADLINE_MUST_BE_FUTURE"

    # Contribution
    INVALID_CONTRIBUTION_AMOUNT = "INVALID_CONTRIBUTION_AMOUNT"
